// src/services/InventoryService.ts

import axios from "axios";// We'll create this shared axios instance next
import { API_ENDPOINTS } from "../config/api";
import type { Product } from "../types";

export const InventoryService = {
  /**
   * Fetch all products for a business
   * @param businessId - Business identifier
   * @returns List of products
   */
  getProducts: async (businessId: string): Promise<Product[]> => {
    const endpoint = API_ENDPOINTS.inventory.productsByBusiness(businessId);
    const res = await axios.get(endpoint);
    return res.data;
  },

  /**
   * Create new product
   * @param product - Product data (partial, ID generated by backend)
   * @returns Created product
   */
  createProduct: async (product: Partial<Product>): Promise<Product> => {
    const res = await axios.post(API_ENDPOINTS.inventory.products, product);
    return res.data;
  },

  /**
   * Update existing product
   * @param productId - Product ID
   * @param updates - Fields to update
   * @returns Updated product
   */
  updateProduct: async (
    productId: string,
    updates: Partial<Product>
  ): Promise<Product> => {
    const endpoint = API_ENDPOINTS.inventory.productById(productId);
    const res = await axios.put(endpoint, updates);
    return res.data;
  },

  /**
   * Delete product
   * @param productId - Product ID
   * @returns Promise resolved when deleted
   */
  deleteProduct: async (productId: string): Promise<void> => {
    const endpoint = API_ENDPOINTS.inventory.productById(productId);
    await axios.delete(endpoint);
  },
};

export default InventoryService;