// src/services/SalesService.ts

import axios from "axios"; // Shared axios instance with auth & refresh
import { API_ENDPOINTS } from "../config/api";
import type { Sale } from "../types";

export const SalesService = {
  /**
   * Create new sale transaction
   * @param sale - Sale data (partial, ID generated by backend)
   * @returns Created sale with ID
   */
  createSale: async (sale: Partial<Sale>): Promise<Sale> => {
    const res = await axios.post(API_ENDPOINTS.sales.base, sale);
    return res.data;
  },

  /**
   * Get sales for a date range
   * @param businessId - Business identifier
   * @param startDate - Start date
   * @param endDate - End date
   * @returns List of sales
   */
  getSales: async (
    businessId: string,
    startDate: Date,
    endDate: Date
  ): Promise<Sale[]> => {
    const params = {
      businessId,
      startDate: startDate.toISOString(),
      endDate: endDate.toISOString(),
    };

    const res = await axios.get(API_ENDPOINTS.sales.list, { params });
    return res.data;
  },

  /**
   * Void a sale transaction
   * @param saleId - Sale ID
   * @returns Updated (voided) sale
   */
  voidSale: async (saleId: string): Promise<Sale> => {
    const endpoint = API_ENDPOINTS.sales.void(saleId);
    const res = await axios.post(endpoint);
    return res.data;
  },
};

export default SalesService;